name: Deploy Globe-Fare Backend to EC2

on:
  push:
    branches:
      - aws-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Backend to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.EC2_PATH }}/globe-fare-adaptive  # ✅ sadece backend dizinine git
            git pull origin aws-dev
            npm install --production
            pm2 restart globe-fare || pm2 start index.js --name=globe-fare
          EOF
